<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wrs_cell_v2">

    <xacro:property name="arm_prefix" value="ur5_"/>

    <!-- ur5 -->
    <xacro:arg name="use_fake_hardware" default="false"/>
    <xacro:arg name="fake_sensor_commands" default="false"/>
    <xacro:arg name="robot_ip" default="192.168.1.102"/>
    

    <!-- suction gripper properties -->
    <xacro:property name="thickness_of_the_suction_cup" value="0.035" /> <!-- 35mm -->
    
    <!-- Include official UR5e description from ur_description package -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

    <!-- gripper -->
    <xacro:arg name="com_port" default="/dev/ttyUSB0" />

    <!-- cobot station height-->
    <xacro:property name="cobot_station_height" value="0.91"/>

    <!-- arm -->
    <!-- Instantiate UR5e arm with official macro -->
    <xacro:arg name="initial_positions_file" default="$(find wrs_env_v2_moveit_config)/config/initial_positions.yaml" />
    <xacro:property name="initial_positions" value="${xacro.load_yaml('$(arg initial_positions_file)')['initial_positions']}"/>
    <xacro:ur_robot
        name="ur5e"
        tf_prefix="${arm_prefix}"
        parent="robot_base"
        use_fake_hardware="$(arg use_fake_hardware)"
        fake_sensor_commands="$(arg fake_sensor_commands)"
        joint_limits_parameters_file="$(find ur_description)/config/ur5e/joint_limits.yaml"
        kinematics_parameters_file="$(find ur_description)/config/ur5e/default_kinematics.yaml"
        physical_parameters_file="$(find ur_description)/config/ur5e/physical_parameters.yaml"
        visual_parameters_file="$(find ur_description)/config/ur5e/visual_parameters.yaml"
        initial_positions="${initial_positions}">
        <origin xyz="${-0.27/2} -.012 0.015" rpy="0 0 ${pi}"/>
    </xacro:ur_robot>

    <!-- World link -->
    <link name="world" />

    <!-- Robot Base -->
    <link name="robot_base">
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/visual/BancaleUR.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/collision/BancaleUR_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="275.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="world_to_base_joint" type="fixed">
        <parent link="world"/>
        <child link="robot_base"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${arm_prefix}flange_rotated_link" />
    <joint name="${arm_prefix}flange_rotated_joint" type="fixed">
        <parent link="${arm_prefix}flange"/>
        <child link="${arm_prefix}flange_rotated_link"/>
        <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
    </joint>
    <!-- Gripper adapter -->
    <link name="${arm_prefix}gripper_adapter">
      <visual>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark_grey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="2.073e-05   1.45286e-03  -1.1049e-03" rpy="0 0 0" />
        <mass value="0.168" />
        <inertia ixx="6.69695624e-05" ixy="5.21511788e-09" ixz="-2.74383009e-08" 
                 iyy="7.85088161e-05" iyz="5.41105193e-07" izz="1.41819717e-04"/>
      </inertial>
    </link>


    <joint name="${arm_prefix}gripper_adapter_joint" type="fixed">
      <origin xyz="-0.006 0 0" rpy="0 ${pi/2} 0" />
      <parent link="${arm_prefix}flange_rotated_link"/>
      <child link="${arm_prefix}gripper_adapter"/>
    </joint>

    <!-- ======================================== Robotiq gripper ======================================== -->
    <link name="${arm_prefix}robotiq_attaching_point" />
    <link name="${arm_prefix}robotiq_coupler_link" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/RobotiqCoupler.dae" />
            </geometry>
        </visual>
    </link>
    <joint name="${arm_prefix}robotiq_coupler_joint" type="fixed">
        <parent link="${arm_prefix}robotiq_attaching_point"/>
        <child link="${arm_prefix}robotiq_coupler_link"/>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
    </joint>
    <!-- gripper tcp offset - from base of the robotiq to tip of the fingers in closed position -->
    <!-- reference: https://assets.robotiq.com/website-assets/support_documents/document/online/2F-85_2F-140_TM_InstructionManual_HTML5_20190503.zip/2F-85_2F-140_TM_InstructionManual_HTML5/Content/6.%20Specifications.htm -->
    <xacro:property name="gripper_tcp_offset" value="0.2333" /> <!--without coupling thickness -->
    <xacro:property name="robotiq_coupling_thickness" value="0.0169" />
    <joint name="${arm_prefix}robotiq_attaching_point_joint" type="fixed">
        <parent link="${arm_prefix}flange_rotated_link"/>
        <child link="${arm_prefix}robotiq_attaching_point"/>
        <origin xyz="0.052123 0.0 0.037123" rpy="0 -${pi/4} 0"/>
    </joint>
    <!-- <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_85_macro.urdf.xacro" /> -->
    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_140_macro.urdf.xacro" />
    <xacro:robotiq_gripper name="RobotiqGripperHardwareInterface" prefix="${arm_prefix}"
        parent="${arm_prefix}robotiq_attaching_point" use_fake_hardware="$(arg use_fake_hardware)" com_port="$(arg com_port)">
        <origin xyz="0 ${-robotiq_coupling_thickness} 0" rpy="${pi/2} 0 0"/>
    </xacro:robotiq_gripper>

    <!-- Robotiq Gripper Tool Center Point (TCP) - Frame between gripper fingers -->
    <link name="${arm_prefix}gripper_tcp" />
    <joint name="${arm_prefix}gripper_tcp_joint" type="fixed">
        <parent link="${arm_prefix}robotiq_attaching_point"/>
        <child link="${arm_prefix}gripper_tcp"/>
        <!-- Position at the center between the gripper fingers -->
        <!--origin xyz="0.0 0.0 0.252" rpy="0 0 0"/> TODO: hardcoded value -->
        <origin xyz="${gripper_tcp_offset + robotiq_coupling_thickness} 0 0" rpy="0 ${pi/2} 0"/>
    </joint>

    <!-- suction gripper mount frame - represents the position of the center of the branch to which the suction gripper is mounted -->
    <link name="${arm_prefix}suction_gripper_attaching_point" />
    <joint name="${arm_prefix}suction_gripper_attaching_point_joint" type="fixed">
        <parent link="${arm_prefix}flange_rotated_link"/>
        <child link="${arm_prefix}suction_gripper_attaching_point"/>
        <origin xyz="0.052123 0.0 -0.037123" rpy="0 ${pi/2 + pi/4} 0"/>
    </joint>
    <!-- add suction gripper  -->
    <link name="${arm_prefix}suction_gripper" >
        <visual>
            <geometry>
                <!-- <mesh filename="package://robot_description/meshes/suction_gripper/visual/SuctionCupHolder.stl" scale="0.001 0.001 0.001" /> -->
                <mesh filename="package://robot_description/meshes/suction_gripper/visual/SuctionCupHolder.dae" />
            </geometry>
            <material name="dark_grey">
            <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robot_description/meshes/suction_gripper/collision/SuctionCupHolder.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="0.2" />
            <inertia ixx="0.00001" ixy="0.000000" ixz="0.000000" 
                     iyy="0.00001" iyz="0.000000" izz="0.00001"/>
        </inertial>
    </link>
    <joint name="${arm_prefix}suction_gripper_joint" type="fixed">
        <parent link="${arm_prefix}suction_gripper_attaching_point"/>
        <child link="${arm_prefix}suction_gripper"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 ${pi/2}"/>
    </joint>

    <!-- Suction Cup Tool Center Point (TCP) - Frame between suction cup -->
    <link name="${arm_prefix}suction_tcp" />
    <joint name="${arm_prefix}suction_tcp_joint" type="fixed">
        <parent link="${arm_prefix}suction_gripper_attaching_point"/>
        <child link="${arm_prefix}suction_tcp"/>
        <origin xyz="0 0 ${0.084 + thickness_of_the_suction_cup}" rpy="0 0 0"/>
    </joint>

    <!-- add camera pillar -->
    <!-- <link name="camera_pillar_link1" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" scale="1.0 1.0 8.0"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.8"/>
            </geometry>
        </collision> </link>
    <link name="camera_pillar_link2" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" scale="1.0 1.0 8.0"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.8"/>
            </geometry>
        </collision> </link>
    <link name="camera_pillar_link3_horizontal" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" scale="1.0 1.0 7.2"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.72"/>
            </geometry>
        </collision> </link>
    <link name="camera_pillar_link4_vertical" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" scale="1.0 1.0 5.0"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.5"/>
            </geometry>
        </collision> </link>

    <joint name="camera_pillar_joint1" type="fixed">
        <parent link="world"/>
        <child link="camera_pillar_link1"/>
        <origin xyz="${-0.72+0.030/2} -0.96 0.4" rpy="0 0 0"/>  </joint>
    <joint name="camera_pillar_joint2" type="fixed">`
        <parent link="world"/>
        <child link="camera_pillar_link2"/>
        <origin xyz="${-0.72+0.030/2+0.15} -0.96 0.4" rpy="0 0 0"/> </joint>

    <joint name="camera_pillar_joint3_horizontal" type="fixed">
        <parent link="world"/>
        <child link="camera_pillar_link3_horizontal"/>
        <origin xyz="${-0.72/2} -0.96 ${0.8+0.030/2}" rpy="0 ${pi/2} 0"/> </joint>
    <joint name="camera_pillar_joint4_vertical" type="fixed"> 
        <parent link="world"/>
        <child link="camera_pillar_link4_vertical"/>
        <origin xyz="${0.04/2} -0.96 ${0.8}" rpy="0 0 0"/> </joint>-->
    
    <!-- define camera link -->
    <!-- <link name="camera_link" /> -->
    <!-- <joint name="camera_to_world_joint" type="fixed">
        <parent link="camera_pillar_link1"/>
        <child link="camera_link"/>
        <origin xyz="-0.56 -0.96 1.0" rpy="0 0 0"/>
    </joint> -->

    <!-- camera holder in the front -->
    <link name="camera_pillar_link1" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" scale="1.0 1.0 8.0"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.8"/>
            </geometry>
        </collision> </link>
    <joint name="camera_pillar_joint1" type="fixed">
        <parent link="world"/>
        <child link="camera_pillar_link1"/>
        <origin xyz="${0.030/2} -0.96 0.4" rpy="0 0 0"/>  </joint>

    

    <!-- Rail -->
    <xacro:property name="rail_length" value="2.0"/>
    <xacro:property name="rail_width" value="0.8"/>
    <xacro:property name="rail_height" value="0.745"/>
    <link name="rail_link">
        <visual>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="100"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial> </link>
    <joint name="world_to_rail_joint" type="fixed">
        <parent link="world"/>
        <child link="rail_link"/>
        <origin xyz="${rail_width/2 + 0.1} ${0/2} ${-cobot_station_height+rail_height/2}" rpy="0 0 ${pi/2}"/> </joint>

    <!-- Add the jigs on the table  -->
        <!-- four jigs for the flat box storage -->
        <xacro:property name="flat_box_storage_jig_size" value="0.04"/> <!-- UPDATE THIS -->
        <xacro:property name="box_height" value="0.215"/> <!-- UPDATE THIS -->
        <xacro:property name="box_width" value="0.1"/> <!-- UPDATE THIS -->
        <xacro:property name="box_length" value="0.24"/> <!-- UPDATE THIS -->
        <xacro:property name="flatBoxStorage_corner_x" value="-0.48"/> <!-- UPDATE THIS - should match the boxAssembling/jig/x value in `wrs_setup.yaml` -->
        <xacro:property name="flatBoxStorage_corner_y" value="-0.35"/> <!-- UPDATE THIS - should match the boxAssembling/jig/y value in `wrs_setup.yaml` -->
        
        <link name="flat_box_storage_jig1_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" />
                </geometry>
                <material name="dark_grey">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${flat_box_storage_jig_size} ${flat_box_storage_jig_size} 0.1"/>
                </geometry>
            </collision>    </link>
        <link name="flat_box_storage_jig2_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" />
                </geometry>
                <material name="dark_grey">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${flat_box_storage_jig_size} ${flat_box_storage_jig_size} 0.1"/>
                </geometry>
            </collision>    </link>
        <link name="flat_box_storage_jig3_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" />
                </geometry>
                <material name="dark_grey">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${flat_box_storage_jig_size} ${flat_box_storage_jig_size} 0.1"/>
                </geometry>
            </collision>    </link>
        <link name="flat_box_storage_jig4_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/bosch_40_40_100.stl" />
                </geometry>
                <material name="dark_grey">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${flat_box_storage_jig_size} ${flat_box_storage_jig_size} 0.1"/>
                </geometry>
            </collision>    </link>
        <joint name="world_to_flat_box_storage_jig1_joint" type="fixed">
            <parent link="world"/> <child link="flat_box_storage_jig1_link"/>
            <origin xyz="${flatBoxStorage_corner_x+flat_box_storage_jig_size/2} ${flatBoxStorage_corner_y} 0.05" rpy="0 0 0"/> </joint>
        <joint name="world_to_flat_box_storage_jig2_joint" type="fixed">
            <parent link="world"/> <child link="flat_box_storage_jig2_link"/>
            <origin xyz="${flatBoxStorage_corner_x+flat_box_storage_jig_size/2} ${flatBoxStorage_corner_y-box_length} 0.05" rpy="0 0 0"/> </joint>
        <joint name="world_to_flat_box_storage_jig3_joint" type="fixed">
            <parent link="world"/>
            <child link="flat_box_storage_jig3_link"/>
            <origin xyz="${flatBoxStorage_corner_x+flat_box_storage_jig_size/2-0.04} ${flatBoxStorage_corner_y-box_length-box_width-flat_box_storage_jig_size/2} 0.05" rpy="0 0 0"/> </joint>
        <joint name="world_to_flat_box_storage_jig4_joint" type="fixed">
            <parent link="world"/> <child link="flat_box_storage_jig4_link"/>
            <origin xyz="${flatBoxStorage_corner_x+flat_box_storage_jig_size/2-0.14} ${flatBoxStorage_corner_y-box_length-box_width-flat_box_storage_jig_size/2} 0.05" rpy="0 0 0"/> </joint>

    
        <!-- add the tool holder -->
        <link name="tool_holder_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/ToolHolder.stl" />
                </geometry>
                <material name="dark_grey">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://robot_description/meshes/ToolHolder.stl" />
                </geometry>
            </collision> </link>
        <joint name="world_to_tool_holder_joint" type="fixed">
            <parent link="world"/> <child link="tool_holder_link"/>
            <origin xyz="${-0.6} ${-0.07} ${0.1}" rpy="0 0 0"/> </joint>

        <!-- add beak tool inside the tool holder -->
        <!-- <link name="beak_tool_link" >
            <visual>
                <geometry>
                    <mesh filename="package://robot_description/meshes/BeakTool.stl" />
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://robot_description/meshes/BeakTool.stl" />
                </geometry>
            </collision> </link>
        <joint name="tool_holder_to_beak_tool_joint" type="fixed">
            <parent link="tool_holder_link"/> <child link="beak_tool_link"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/> </joint> -->
    <!-- Temporarity add a bottle on the table -->
    <link name="bottle1_link" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bottle.glb" />
            </geometry>
        </visual> </link>
    <link name="bottle2_link" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/bottle.glb" />
            </geometry>
        </visual> </link>
    <joint name="world_to_bottle1_joint" type="fixed">
        <parent link="world"/>
        <child link="bottle1_link"/>
        <origin xyz="0.4 -0.3 ${-0.165+0.205/2}" rpy="${pi/2} 0 ${pi/2}"/> </joint>
    <joint name="world_to_bottle2_joint" type="fixed">
        <parent link="world"/>
        <child link="bottle2_link"/>
        <origin xyz="0.3 -0.5 ${-0.165+0.205/2}" rpy="${pi/2} 0 ${pi/3}"/> </joint>

</robot>
