<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wrs_cell_v2">

    <xacro:property name="arm_prefix" value="ur5_"/>

    <!-- ur5 -->
    <xacro:arg name="use_fake_hardware" default="false"/>
    <xacro:arg name="fake_sensor_commands" default="false"/>
    <xacro:arg name="robot_ip" default="192.168.1.102"/>

    <!-- gripper tcp offset - from base of the robotiq to tip of the fingers in closed position -->
    <!-- reference: https://assets.robotiq.com/website-assets/support_documents/document/online/2F-85_2F-140_TM_InstructionManual_HTML5_20190503.zip/2F-85_2F-140_TM_InstructionManual_HTML5/Content/6.%20Specifications.htm -->
    <xacro:property name="gripper_tcp_offset" value="0.1628" /> <!--might add 14mm if added the coulping piece -->
    
    <!-- Include official UR5e description from ur_description package -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

    <!-- gripper -->
    <xacro:arg name="com_port" default="/dev/ttyUSB0" />
    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_85_macro.urdf.xacro" />

    <!-- arm -->
    <!-- Instantiate UR5e arm with official macro -->
    <xacro:arg name="initial_positions_file" default="$(find wrs_env_v2_moveit_config)/config/initial_positions.yaml" />
    <xacro:property name="initial_positions" value="${xacro.load_yaml('$(arg initial_positions_file)')['initial_positions']}"/>
    <xacro:ur_robot
        name="ur5e"
        tf_prefix="${arm_prefix}"
        parent="robot_base"
        use_fake_hardware="$(arg use_fake_hardware)"
        fake_sensor_commands="$(arg fake_sensor_commands)"
        joint_limits_parameters_file="$(find ur_description)/config/ur5e/joint_limits.yaml"
        kinematics_parameters_file="$(find ur_description)/config/ur5e/default_kinematics.yaml"
        physical_parameters_file="$(find ur_description)/config/ur5e/physical_parameters.yaml"
        visual_parameters_file="$(find ur_description)/config/ur5e/visual_parameters.yaml"
        initial_positions="${initial_positions}">
        <origin xyz="${-0.27/2} ${-0.27/2} 0.015" rpy="0 0 0"/>
    </xacro:ur_robot>

    <!-- World link -->
    <link name="world" />

    <!-- Robot Base -->
    <link name="robot_base">
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/visual/BancaleUR.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/collision/BancaleUR_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="275.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="world_to_base_joint" type="fixed">
        <parent link="world"/>
        <child link="robot_base"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Gripper adapter -->
    <link name="${arm_prefix}gripper_adapter">
      <visual>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <!-- TODO: check inertia -->
      <inertial>
        <origin xyz="2.073e-05   1.45286e-03  -1.1049e-03" rpy="0 0 0" />
        <mass value="0.168" />
        <inertia ixx="6.69695624e-05" ixy="5.21511788e-09" ixz="-2.74383009e-08" 
                 iyy="7.85088161e-05" iyz="5.41105193e-07" izz="1.41819717e-04"/>
      </inertial>
    </link>

    <joint name="${arm_prefix}gripper_adapter_joint" type="fixed">
      <origin xyz="-0.006 0 0" rpy="0 ${pi/2.0} 0" />
      <parent link="${arm_prefix}flange"/>
      <child link="${arm_prefix}gripper_adapter"/>
    </joint>

    <!-- Attach the robotiq 85 gripper -->
    <xacro:robotiq_gripper name="RobotiqGripperHardwareInterface" prefix="${arm_prefix}" parent="${arm_prefix}gripper_adapter" use_fake_hardware="$(arg use_fake_hardware)" com_port="$(arg com_port)">
        <origin xyz="-0.03299 0.0 0.07114" rpy="${0} ${pi/2-5*pi/6} 0"/>
    </xacro:robotiq_gripper>

    <!-- Robotiq Gripper Tool Center Point (TCP) - Frame between gripper fingers -->
    <link name="${arm_prefix}gripper_tcp" />
    <joint name="${arm_prefix}gripper_tcp_joint" type="fixed">
        <parent link="${arm_prefix}robotiq_85_base_link"/>
        <child link="${arm_prefix}gripper_tcp"/>
        <!-- Position at the center between the gripper fingers -->
        <origin xyz="0.0 0.0 ${gripper_tcp_offset}" rpy="0 0 0"/>
    </joint>

    <!-- Suction Cup Tool Center Point (TCP) - Frame between suction cup -->
    <link name="${arm_prefix}suction_tcp" />
    <joint name="${arm_prefix}suction_tcp_joint" type="fixed">
        <parent link="${arm_prefix}gripper_adapter"/>
        <child link="${arm_prefix}suction_tcp"/>
        <!-- Position at the center between the gripper fingers -->
        <origin xyz="0.03299 0.0 0.07114" rpy="0 ${pi/3} 0"/>
    </joint>

    

    <!-- Rail -->
    <xacro:property name="rail_length" value="2.0"/>
    <xacro:property name="rail_width" value="0.8"/>
    <xacro:property name="rail_height" value="0.8"/>
    <link name="rail_link">
        <visual>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="100"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="world_to_rail_joint" type="fixed">
        <parent link="world"/>
        <child link="rail_link"/>
        <origin xyz="${rail_width/2 + 0.1} ${0/2} ${-rail_height/2 - 0.1}" rpy="0 0 ${pi/2}"/>
    </joint>

</robot>
