<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wrs_cell_v2">

    <xacro:property name="arm_prefix" value="ur5_"/>

    <!-- ur5 -->
    <xacro:arg name="use_fake_hardware" default="false"/>
    <xacro:arg name="fake_sensor_commands" default="false"/>
    <xacro:arg name="robot_ip" default="192.168.1.102"/>
    

    <!-- suction gripper properties -->
    <xacro:property name="thickness_of_the_suction_cup" value="0.016" /> <!-- 16mm -->
    
    <!-- Include official UR5e description from ur_description package -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

    <!-- gripper -->
    <xacro:arg name="com_port" default="/dev/ttyUSB0" />

    <!-- cobot station height-->
    <xacro:property name="cobot_station_height" value="0.91"/>

    <!-- arm -->
    <!-- Instantiate UR5e arm with official macro -->
    <xacro:arg name="initial_positions_file" default="$(find wrs_env_v2_moveit_config)/config/initial_positions.yaml" />
    <xacro:property name="initial_positions" value="${xacro.load_yaml('$(arg initial_positions_file)')['initial_positions']}"/>
    <xacro:ur_robot
        name="ur5e"
        tf_prefix="${arm_prefix}"
        parent="robot_base"
        use_fake_hardware="$(arg use_fake_hardware)"
        fake_sensor_commands="$(arg fake_sensor_commands)"
        joint_limits_parameters_file="$(find ur_description)/config/ur5e/joint_limits.yaml"
        kinematics_parameters_file="$(find ur_description)/config/ur5e/default_kinematics.yaml"
        physical_parameters_file="$(find ur_description)/config/ur5e/physical_parameters.yaml"
        visual_parameters_file="$(find ur_description)/config/ur5e/visual_parameters.yaml"
        initial_positions="${initial_positions}">
        <origin xyz="${-0.27/2} -.012 0.015" rpy="0 0 ${pi}"/>
    </xacro:ur_robot>

    <!-- World link -->
    <link name="world" />

    <!-- Robot Base -->
    <link name="robot_base">
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/visual/BancaleUR.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robot_description/meshes/cobot_station/collision/BancaleUR_collision.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="275.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="world_to_base_joint" type="fixed">
        <parent link="world"/>
        <child link="robot_base"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${arm_prefix}flange_rotated_link" />
    <joint name="${arm_prefix}flange_rotated_joint" type="fixed">
        <parent link="${arm_prefix}flange"/>
        <child link="${arm_prefix}flange_rotated_link"/>
        <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
    </joint>
    <!-- Gripper adapter -->
    <link name="${arm_prefix}gripper_adapter">
      <visual>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark_grey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://robot_description/meshes/gripper_adapter.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="2.073e-05   1.45286e-03  -1.1049e-03" rpy="0 0 0" />
        <mass value="0.168" />
        <inertia ixx="6.69695624e-05" ixy="5.21511788e-09" ixz="-2.74383009e-08" 
                 iyy="7.85088161e-05" iyz="5.41105193e-07" izz="1.41819717e-04"/>
      </inertial>
    </link>


    <joint name="${arm_prefix}gripper_adapter_joint" type="fixed">
      <origin xyz="-0.006 0 0" rpy="0 ${pi/2} 0" />
      <parent link="${arm_prefix}flange_rotated_link"/>
      <child link="${arm_prefix}gripper_adapter"/>
    </joint>

    <!-- ======================================== Robotiq gripper ======================================== -->
    <link name="${arm_prefix}robotiq_attaching_point" />
    <link name="${arm_prefix}robotiq_coupler_link" >
        <visual>
            <geometry>
                <mesh filename="package://robot_description/meshes/RobotiqCoupler.dae" />
            </geometry>
        </visual>
    </link>
    <joint name="${arm_prefix}robotiq_coupler_joint" type="fixed">
        <parent link="${arm_prefix}robotiq_attaching_point"/>
        <child link="${arm_prefix}robotiq_coupler_link"/>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
    </joint>
    <!-- gripper tcp offset - from base of the robotiq to tip of the fingers in closed position -->
    <!-- reference: https://assets.robotiq.com/website-assets/support_documents/document/online/2F-85_2F-140_TM_InstructionManual_HTML5_20190503.zip/2F-85_2F-140_TM_InstructionManual_HTML5/Content/6.%20Specifications.htm -->
    <xacro:property name="gripper_tcp_offset" value="0.2333" /> <!--without coupling thickness -->
    <xacro:property name="robotiq_coupling_thickness" value="0.0169" />
    <joint name="${arm_prefix}robotiq_attaching_point_joint" type="fixed">
        <parent link="${arm_prefix}flange_rotated_link"/>
        <child link="${arm_prefix}robotiq_attaching_point"/>
        <origin xyz="0.052123 0.0 0.037123" rpy="0 -${pi/4} 0"/>
    </joint>
    <!-- <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_85_macro.urdf.xacro" /> -->
    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_140_macro.urdf.xacro" />
    <xacro:robotiq_gripper name="RobotiqGripperHardwareInterface" prefix="${arm_prefix}"
        parent="${arm_prefix}robotiq_attaching_point" use_fake_hardware="$(arg use_fake_hardware)" com_port="$(arg com_port)">
        <origin xyz="0 ${-robotiq_coupling_thickness} 0" rpy="${pi/2} 0 0"/>
    </xacro:robotiq_gripper>

    <!-- Robotiq Gripper Tool Center Point (TCP) - Frame between gripper fingers -->
    <link name="${arm_prefix}gripper_tcp" />
    <joint name="${arm_prefix}gripper_tcp_joint" type="fixed">
        <parent link="${arm_prefix}robotiq_attaching_point"/>
        <child link="${arm_prefix}gripper_tcp"/>
        <!-- Position at the center between the gripper fingers -->
        <!--origin xyz="0.0 0.0 0.252" rpy="0 0 0"/> TODO: hardcoded value -->
        <origin xyz="${gripper_tcp_offset + robotiq_coupling_thickness} 0 0" rpy="0 ${pi/2} 0"/>
    </joint>

    <!-- suction gripper mount frame - represents the position of the center of the branch to which the suction gripper is mounted -->
    <link name="${arm_prefix}suction_gripper_attaching_point" />
    <joint name="${arm_prefix}suction_gripper_attaching_point_joint" type="fixed">
        <parent link="${arm_prefix}flange_rotated_link"/>
        <child link="${arm_prefix}suction_gripper_attaching_point"/>
        <origin xyz="0.052123 0.0 -0.037123" rpy="0 ${pi/2 + pi/4} 0"/>
    </joint>
    <!-- add suction gripper  -->
    <link name="${arm_prefix}suction_gripper" >
        <visual>
            <geometry>
                <!-- <mesh filename="package://robot_description/meshes/suction_gripper/visual/SuctionCupHolder.stl" scale="0.001 0.001 0.001" /> -->
                <mesh filename="package://robot_description/meshes/suction_gripper/visual/SuctionCupHolder.dae" />
            </geometry>
            <material name="dark_grey">
            <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robot_description/meshes/suction_gripper/collision/SuctionCupHolder.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="0.2" />
            <inertia ixx="0.00001" ixy="0.000000" ixz="0.000000" 
                     iyy="0.00001" iyz="0.000000" izz="0.00001"/>
        </inertial>
    </link>
    <joint name="${arm_prefix}suction_gripper_joint" type="fixed">
        <parent link="${arm_prefix}suction_gripper_attaching_point"/>
        <child link="${arm_prefix}suction_gripper"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 ${pi/2}"/>
    </joint>

    <!-- Suction Cup Tool Center Point (TCP) - Frame between suction cup -->
    <link name="${arm_prefix}suction_tcp" />
    <joint name="${arm_prefix}suction_tcp_joint" type="fixed">
        <parent link="${arm_prefix}suction_gripper_attaching_point"/>
        <child link="${arm_prefix}suction_tcp"/>
        <origin xyz="0 0 ${0.084 + thickness_of_the_suction_cup}" rpy="0 0 0"/>
    </joint>

    <!-- add camera pillar -->
    <link name="camera_pillar_link" >
        <visual>
            <geometry>
                <box size="0.08 0.08 0.997"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.08 0.08 0.997"/>
            </geometry>
        </collision>
    </link>
    <joint name="camera_pillar_joint" type="fixed">
        <parent link="world"/>
        <child link="camera_pillar_link"/>
        <origin xyz="-0.06 -0.96 0.0" rpy="0 0 0"/>
    </joint>

    <!-- define camera link -->
    <link name="camera_link" />
    <joint name="camera_to_worldjoint" type="fixed">
        <parent link="camera_pillar_link"/>
        <child link="camera_link"/>
        <origin xyz="-0.06 -0.96 1.0" rpy="0 0 0"/>
    </joint>

    

    <!-- Rail -->
    <xacro:property name="rail_length" value="2.0"/>
    <xacro:property name="rail_width" value="0.8"/>
    <xacro:property name="rail_height" value="0.745"/>
    <link name="rail_link">
        <visual>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${rail_length} ${rail_width} ${rail_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="100"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="world_to_rail_joint" type="fixed">
        <parent link="world"/>
        <child link="rail_link"/>
        <origin xyz="${rail_width/2 + 0.1} ${0/2} ${-cobot_station_height+rail_height/2}" rpy="0 0 ${pi/2}"/>
    </joint>

</robot>
